turtlebot3_waffle_sim:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------
  left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: LFW
    pid: {p: 20.0, i: 0.1, d: 0.01}
  right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: RFW
    pid: {p: 20.0, i: 0.1, d: 0.01}
  suspension_one:
    type: effort_controllers/JointPositionController
    joint: LFS
    pid: {p: 100, i: 0.0000, d: 30}
  suspension_two:
    type: effort_controllers/JointPositionController
    joint: RFS
    pid: {p: 100, i: 0.0000, d: 30}
  suspension_three:
    type: effort_controllers/JointPositionController
    joint: LBS
    pid: {p: 100, i: 0.0000, d: 30}
  suspension_four:
    type: effort_controllers/JointPositionController
    joint: RBS
    pid: {p: 100, i: 0.0000, d: 30}

